/* Keeps content/ in step with the app.
 *
 *   node tools/sync-content.mjs           rewrite the generated files
 *   node tools/sync-content.mjs --check   fail if they are out of date (CI)
 *
 * index.html is the source of record for content. It has no build step by
 * design, so the vocabulary lives in the page itself and content/*.json is a
 * generated export — the README used to call it the "authoring source", which
 * was how the two silently drifted apart (the JSON was missing a whole root
 * family and six words, and each file carried fields the other lacked).
 *
 * Fields the app does not hold — a root's transliteration, a word's part of
 * speech, a letter's name transliteration and emphatic flag — are annotations
 * that live only in the JSON. They are carried across on regeneration and
 * reported when a new entry is missing them.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const p = f => path.join(ROOT, f);
const check = process.argv.includes('--check');

/* ---------- read the app's content ---------- */
const html = fs.readFileSync(p('index.html'), 'utf8');
const grab = (name, open, close) => {
  const m = html.match(new RegExp(`var ${name} = (\\${open}[\\s\\S]*?\\n\\${close});`));
  if (!m) throw new Error(`could not find ${name} in index.html`);
  return eval(`(${m[1]})`);
};
const ALPHABET = grab('ALPHABET', '[', ']');
const LETTER_META = grab('LETTER_META', '{', '}');
const ROOTS = grab('ROOTS', '[', ']');

/* ---------- carry annotations forward ---------- */
const prevWords = JSON.parse(fs.readFileSync(p('content/roots-words.json'), 'utf8'));
const prevLetters = JSON.parse(fs.readFileSync(p('content/letters.json'), 'utf8'));
const rootAnn = new Map(prevWords.roots.map(r => [r.id, r]));
const wordAnn = new Map(prevWords.words.map(w => [w.id, w]));
const letterAnn = new Map(prevLetters.letters.map(l => [l.key, l]));
const gaps = [];

/* ---------- roots-words.json ---------- */
const GENERATED = 'GENERATED by tools/sync-content.mjs from index.html — do not edit the ' +
  'generated fields by hand; change index.html and re-run. ';
const wordsDoc = {
  _comment: GENERATED +
    'Roots are first-class [R-3] and every word is fully diacritized [R-35] and register-tagged [R-30]. ' +
    'Verbs are cited as past 3ms (dictionary form); nouns without case endings. ' +
    'Ids are permanent: append new ones, never renumber — saved learner progress is keyed on them. ' +
    '`translit` on a root and `pos` on a word are hand annotations kept only here and carried across ' +
    'regeneration. NOT yet native-speaker reviewed — see the README content accuracy note.',
  roots: ROOTS.map(r => {
    const a = rootAnn.get(r.id);
    if (!a) gaps.push(`root ${r.id} (${r.root}) has no translit — add it to content/roots-words.json`);
    return { id: r.id, consonants: r.root, translit: a ? a.translit : '', meaning: r.meaning };
  }),
  words: ROOTS.flatMap(r => r.words.map(w => {
    const a = wordAnn.get(w.id);
    if (!a) gaps.push(`word ${w.id} (${w.ar}) has no pos — add it to content/roots-words.json`);
    return { id: w.id, root: r.id, ar: w.ar, translit: w.t, en: w.en,
             pos: a ? a.pos : '', register: w.reg, audio: w.a };
  })),
};

/* ---------- letters.json ---------- */
const lettersDoc = {
  _comment: GENERATED +
    'The 28 letters with all four positional forms, stored as pre-shaped strings (tatweel U+0640 ' +
    'supplies the joining context, so browsers render the correct contextual glyph). Non-connectors ' +
    '(ا د ذ ر ز و) do not join forward: initial = isolated, medial = final. `guttural` follows design ' +
    'doc §2.2 (ح ع خ غ ق). `name_translit` and `emphatic` are hand annotations kept only here; ' +
    '`emphatic` (ص ض ط ظ) is data for audio prioritization per [R-33], not a UI feature.',
  letters: ALPHABET.map(a => {
    const M = LETTER_META[a.id], ann = letterAnn.get(M.key);
    if (!ann) gaps.push(`letter ${M.key} has no name_translit/emphatic — add it to content/letters.json`);
    return {
      key: M.key, ar: a.letter, name: M.an,
      name_translit: ann ? ann.name_translit : '',
      name_en: a.name, translit: a.translit, sound: a.sound,
      example: { ar: a.ex, translit: a.exT, en: a.exE },
      connects_forward: M.forms[1] !== M.forms[0],
      guttural: M.guttural, emphatic: ann ? ann.emphatic : false,
      forms: { isolated: M.forms[0], initial: M.forms[1], medial: M.forms[2], final: M.forms[3] },
    };
  }),
};

/* ---------- recording-list.md ---------- */
const words = ROOTS.flatMap(r => r.words);
const total = ALPHABET.length + words.length;
const recording = [
  `# Recording checklist — ${total} clips`,
  '',
  '<!-- Generated by tools/sync-content.mjs from index.html. Do not edit by hand. -->',
  '',
  'Filenames are exactly what the app requests.',
  'For the native speaker: one clip per row, mp3, mono, quiet room, careful MSA.',
  'Letters: say the letter’s **name**, then its bare **sound** (e.g. “بَاء … بْ”).',
  'Words: say the word **once, clearly**, as diacritized.',
  '',
  `## Letters — save to \`audio/letters/\` (${ALPHABET.length})`,
  '',
  '| file | letter | name | sound |',
  '|---|---|---|---|',
  ...ALPHABET.map(a => `| \`${LETTER_META[a.id].key}.mp3\` | ${a.letter} | ${a.name} | ${a.translit} |`),
  '',
  `## Words — save to \`audio/words/\` (${words.length})`,
  '',
  '| file | word | transliteration | meaning |',
  '|---|---|---|---|',
  ...words.map(w => `| \`${w.a}.mp3\` | ${w.ar} | ${w.t} | ${w.en} |`),
  '',
].join('\n');

/* ---------- integrity checks ---------- */
const problems = [];
const dup = (label, xs) => {
  const seen = new Set(), bad = new Set();
  for (const x of xs) { if (seen.has(x)) bad.add(x); seen.add(x); }
  if (bad.size) problems.push(`duplicate ${label}: ${[...bad].join(', ')}`);
};
dup('root id', ROOTS.map(r => r.id));
dup('word id', words.map(w => w.id));
dup('word form', words.map(w => w.ar));
dup('audio stem', words.map(w => w.a));
dup('letter audio stem', ALPHABET.map(a => LETTER_META[a.id].key));
for (const w of words) {
  if (!/^w-[a-z0-9]+-\d+$/.test(w.id)) problems.push(`word id not in stable form: ${w.id}`);
  if (!/^[a-z0-9_]+$/.test(w.a)) problems.push(`audio stem is not filename-safe: ${w.a} (${w.ar})`);
  if (!['msa', 'egy'].includes(w.reg)) problems.push(`unknown register on ${w.id}: ${w.reg}`);
  /* [R-35]: stored content stays fully diacritized; fading is a render-time
     decision. A word with no vowel marks at all never got them. */
  if (!/[ً-ْٰ]/.test(w.ar)) problems.push(`no diacritics on ${w.id} (${w.ar})`);
}
for (const a of ALPHABET) if (!LETTER_META[a.id]) problems.push(`letter ${a.id} has no LETTER_META entry`);

if (problems.length) {
  console.error('content problems:\n  ' + problems.join('\n  '));
  process.exit(1);
}

/* ---------- write or compare ---------- */
const outputs = [
  ['content/roots-words.json', JSON.stringify(wordsDoc, null, 2) + '\n'],
  ['content/letters.json', JSON.stringify(lettersDoc, null, 2) + '\n'],
  ['content/recording-list.md', recording],
];
let stale = 0;
for (const [file, body] of outputs) {
  const current = fs.existsSync(p(file)) ? fs.readFileSync(p(file), 'utf8') : null;
  if (current === body) { console.log(`  ok    ${file}`); continue; }
  stale++;
  if (check) console.log(`  STALE ${file}`);
  else { fs.writeFileSync(p(file), body); console.log(`  wrote ${file}`); }
}

console.log(`\n${ROOTS.length} root families · ${words.length} words · ${ALPHABET.length} letters · ${total} clips`);
if (gaps.length) console.log('\nmissing annotations:\n  ' + gaps.join('\n  '));

if (check && stale) {
  console.error('\ncontent/ is out of date with index.html — run: node tools/sync-content.mjs');
  process.exit(1);
}
